/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ApiHelloRouteImport } from "./routes/api.hello";
import { Route as ApiFilesIndexRouteImport } from "./routes/api.files.index";
import { Route as ApiFilesKeyRouteImport } from "./routes/api.files.$key";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: "/api/hello",
  path: "/api/hello",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiFilesIndexRoute = ApiFilesIndexRouteImport.update({
  id: "/api/files/",
  path: "/api/files/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiFilesKeyRoute = ApiFilesKeyRouteImport.update({
  id: "/api/files/$key",
  path: "/api/files/$key",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/api/hello": typeof ApiHelloRoute;
  "/api/files/$key": typeof ApiFilesKeyRoute;
  "/api/files/": typeof ApiFilesIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/api/hello": typeof ApiHelloRoute;
  "/api/files/$key": typeof ApiFilesKeyRoute;
  "/api/files": typeof ApiFilesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/api/hello": typeof ApiHelloRoute;
  "/api/files/$key": typeof ApiFilesKeyRoute;
  "/api/files/": typeof ApiFilesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/api/hello" | "/api/files/$key" | "/api/files/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/api/hello" | "/api/files/$key" | "/api/files";
  id: "__root__" | "/" | "/api/hello" | "/api/files/$key" | "/api/files/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ApiHelloRoute: typeof ApiHelloRoute;
  ApiFilesKeyRoute: typeof ApiFilesKeyRoute;
  ApiFilesIndexRoute: typeof ApiFilesIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/hello": {
      id: "/api/hello";
      path: "/api/hello";
      fullPath: "/api/hello";
      preLoaderRoute: typeof ApiHelloRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/files/": {
      id: "/api/files/";
      path: "/api/files";
      fullPath: "/api/files/";
      preLoaderRoute: typeof ApiFilesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/files/$key": {
      id: "/api/files/$key";
      path: "/api/files/$key";
      fullPath: "/api/files/$key";
      preLoaderRoute: typeof ApiFilesKeyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHelloRoute: ApiHelloRoute,
  ApiFilesKeyRoute: ApiFilesKeyRoute,
  ApiFilesIndexRoute: ApiFilesIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
